#!/usr/bin/env bash
# Usage: sub commands
# Summary: List all sub commands
#
# NAME
#   sub commands -- list sub commands
#
# SYNOPSIS
#   sub commands
#
# DESCRIPTION
#   This command is mostly used for autocompletion in various shells, and for
#   `sub help`.

if [[ "$DEBUG" ]]; then
  export PS4='+ [${BASH_SOURCE##*/}:$LINENO] '
  set -x
fi

if [[ -z "$_SUB_ROOT" ]]; then
  echo "Error: Must run \`${0//*\/sub-/sub }' instead."
  exit 1
fi

set -euo pipefail

main() {
  shopt -s nullglob

  {
    for command in "$_SUB_ROOT/libexec/sub-"*; do
      if [[ -x "$command" ]]; then
        echo "${command##*/sub-}"
      fi
    done
  } | sort

  shopt -u nullglob
}

main "$@"
