#!/usr/bin/env bash
# Usage: sub init [options] [--] [-]
# Summary: Initializes Bash/ZSH shell completion for sub commands
#
# NAME
#   sub init -- Initializes Bash/ZSH shell completion for
#   sub commands
#
# SYNOPSIS
#   sub init
#   sub init [options] -
#
# DESCRIPTION
#   Initializes Bash/ZSH shell completion for sub commands. This is
#   NOT required unless you want the convenience of tab completion.
#
# OPTIONS
#   -s shell, --shell shell
#       Specify the shell to initialize for, default is `basename "$SHELL"`
#
# EXAMPLES
#   Add to your `~/.zshenv` or `~/.bash_profile`
#
#     # Setup sub
#     command -v sub > /dev/null && eval "$(sub init -)"

[[ "${DEBUG}" ]] && set -x

set -euo pipefail

while [[ "${#}" -gt 0 ]]; do
  case "${1}" in
    -s | --shell | --shell=*)
      opt="${1%%=*}"
      if [[ "${1:-}" = "--shell="* ]]; then
        shell="${1##--shell=}"
        shift
      elif [[ "${2:-}" ]]; then
        shell="${2}"
        shift 2
      fi

      [[ -z "${shell:-}" ]] &&
        abort "option requires an argument -- '${opt}'"
      ;;
    -s?*)
      shell="${1##-s}"
      shift
      ;;
    --) shift;;
    -) print=1; shift;;
    --*|-*) warn "Invalid option"; exec sub-help --usage --exit 1 "${0##*/sub-}";;
    *) break;;
  esac
done

if [[ -z "${shell:-}" ]]; then
  shell="$(basename "${SHELL}")"
fi

if [[ -z "${print:-}" ]]; then
  case "${shell}" in
    bash)
      # shellcheck disable=SC2088
      profile='~/.bash_profile'
      ;;
    zsh)
      # shellcheck disable=SC2088
      profile='~/.zshenv'
      ;;
    *)
      profile='your profile'
      ;;
  esac

  { echo "# Load sub automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo "eval \"\$(${_SUB_ROOT}/bin/sub init -)\""
  } >&2

  exit 1
fi

case "${shell}" in
  bash | zsh)
    echo "if ! command -v sub > /dev/null; then"
    echo "  export PATH=\"\${PATH}:${_SUB_ROOT}/bin\""
    echo "fi"
    echo
    echo "source \"${_SUB_ROOT}/completions/sub.${shell}\""
    ;;
esac
